version: '3.8'

services:
  todo-app:
    build: .
    container_name: simple-todo-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    volumes:
      # Optional: Mount for development (comment out for production)
      # - ./public:/app/public:ro
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge